export const CATEGORIA_L0_TYPE = {
  MOLINETE: "MOLINETE",
  ALICATE: "ALICATE",
  ANZOL: "ANZOL",
};

export const PRODUCT_SORT_BY = {
  NEWEST_FIRST: "newest",
  OLDEST_FIRST: "oldest",
  ASCENDING: "ascending",
  DESCENDING: "descending",
};

// export const
export const PRODUCT_FIELDS = {
  CODIGO: "CODIGO",
  DESCRIPCION: "DESCRIPCION",
  CODIGO1: "CODIGO1",
  COMPRA: "COMPRA",
  PRECIO: "PRECIO",
  CAJAS: "CAJAS",
  CATEGORIA_L0: "CATEGORIA_L0",
  CATEGORIA_L1: "CATEGORIA_L1",
  MODELO: "MODELO",
  COLOR: "COLOR",
  IMAGE: "IMAGE",
};

export const GROUP_CATEGORIES = {
  PESCA: {
    "Canhas y Carretillas": ["VARA", "CARRETEL", "MOL"],
    "Anzuelos y Cebos": ["ANZOL", "ISCA", "SABIKI"],
    "Loneas y Leaders": ["LINHA", "LEADER"],
    "Accesorios de Pesca": [
      "BOIA",
      "GIRADOR",
      "GIRADOR+SNAP",
      "SNAP",
      "CHICOTE",
      "ILUMINADOR",
      "PUNTA",
      "PUNTERA",
      "ROTOR",
      "PASADOR",
      "ARGOLA",
    ],
    "Herramientas de Pesca": [
      "ESCAMADOR",
      "PLOMADA",
      "CHUMBO",
      "PIESA",
      "PIEZA",
    ],
    "Redes y Trampas": [
      "COVO",
      "PASSAGUA",
      "RED",
      "TARRAFA",
      "CESTA",
      "CESTINHO",
    ],
    "Bolsas y Transportadores": ["SAMBURA"],
    "Equipo de Pesca y Seguridad": ["GAS", "INFLADOR"],
  },

  CAMPING: {
    "Herramientas de Camping": [
      "ALICATE",
      "ARAME",
      "FACA",
      "FIXA",
      "FIXADOR",
      "MANIVELA",
      "SACO",
      "TIRA",
      "TUBO",
      "ESTOJO",
      "HORNO",
    ],
    "Equipo de Camping": [
      "BALANZA",
      "BALDE",
      "BARRACA",
      "BOLSA",
      "BONE",
      "BORRACHA",
      "BOTA",
      "CABO",
      "CADEIRA",
      "CADENA",
      "CANTIL",
      "CAPA",
      "CARR",
      "CHUVEIRO",
      "COLCHON",
      "COLETE",
      "CONJUNTO",
      "EXPOSITOR",
      "JUNTA",
      "LINTERNA",
      "LUVA",
      "MISSANGA",
      "OXIGENADOR",
      "SINO",
      "SOMBRERO",
      "SUPORTE",
      "TIJERA",
      "TIJERITA",
      "TRAVAO",
    ],
    "Accesorios de Camping": [
      "GAS",
      "INFLADOR",
      "CONECTOR",
      "GARATEIA",
      "TAPA",
    ],
    "Seguridad y Protección": ["MOSQUITERO"],
  },
};
